
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Import Database type but rename it to avoid conflict with our local definition
import type { Database as GeneratedDatabase } from './types';

const SUPABASE_URL = "https://fgrjdurorrehxxsmtlbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncmpkdXJvcnJlaHh4c210bGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODg4MjksImV4cCI6MjA1ODg2NDgyOX0.ynqn6yGYGZVxJJnvizeL8ti5Uj6ok93GbgHQYu_yTos";

// Define database types for TypeScript support
export type UserRow = {
  id: string;
  email: string;
  name: string;
  subscription: 'free' | 'premium' | 'unlimited';
  orderLimit: number;
  ordersUsed: number;
  subscription_status: 'active' | 'pending' | 'rejected';
  requested_subscription: string;
};

// Update the Database type to include the users table
export type Database = {
  public: {
    Tables: {
      users: {
        Row: UserRow;
        Insert: Omit<UserRow, 'id'>;
        Update: Partial<UserRow>;
      };
    };
    Views: {
      [_ in never]: never
    };
    Functions: {
      [_ in never]: never
    };
    Enums: {
      [_ in never]: never
    };
    CompositeTypes: {
      [_ in never]: never
    };
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
